blunderbuss:
  ignore_authors:
  - magic-mirror-bot
  ignore_drafts: true
  max_request_count: 2
  request_count: 2
plugins:
  stolostron/policy-collection:
    plugins:
    - dco
    - blunderbuss
triggers:
- repos:
  - stolostron/policy-collection
  trusted_apps:
  - magic-mirror-bot
