blunderbuss:
  ignore_authors:
  - magic-mirror-bot
  ignore_drafts: true
  max_request_count: 2
  request_count: 2
plugins:
  stolostron/governance-policy-addon-controller:
    plugins:
    - dco
    - blunderbuss
triggers:
- repos:
  - stolostron/governance-policy-addon-controller
  trusted_apps:
  - magic-mirror-bot
  - red-hat-trusted-app-pipeline
